[build]
publish = "static"
command = "npm run build"

[functions."ssr"]
included_files = [
  ".nuxt/**",
  "@nuxtjs/axios",
  "fsxa-nuxt-module"
]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/builders/ssr"
status = 200
