[build]
publish = "static"
command = "yarn build"

[functions."ssr"]
included_files = [
  ".nuxt/**",
  "node_modules/@storefront-ui/**",
]

[[redirects]]
from = "/*"
to = "/.netlify/builders/ssr"
status = 200
