[build]
publish = "static"
command = "yarn build"

[build.environment]
NODE_VERSION = "14"

[functions."ssr"]
included_files = [
  ".nuxt/**"
]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/builders/ssr"
status = 200
