[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "14"

[functions."ssr"]
included_files = [
  ".nuxt/**",
  "dist/**",
]

[[redirects]]
from = "/*"
to = "/.netlify/builders/ssr"
status = 200
