[build]
publish = "static"
command = "yarn build"

[functions."ssr"]
included_files = [
  ".nuxt/**",
  "@nuxtjs/axios",
  "fsxa-nuxt-module"
]

[[redirects]]
from = "/*"
to = "/.netlify/builders/ssr"
status = 200
